name: Backend Unit Tests

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - master
      - main
      - develop
  pull_request:
    paths:
      - 'backend/**'
    branches:
      - master
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.pip

    - name: Run unit tests
      working-directory: ./backend
      run: |
        python -m pytest test/unit 
